import { workflow, node, trigger } from '@n8n/workflow-sdk';

const every5 = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.3, config: { name: 'Every 5 Minutes', position: [0, 0], parameters: { rule: { interval: [{ field: 'minutes', minutesInterval: 5 }] } } } });
const sendReminders = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Send Due Reminders', position: [224, 0], executeOnce: true, parameters: { operation: 'executeQuery', query: "WITH due AS (SELECT o.item_id, o.owner_id, o.occurs_at, o.title, o.tz, o.all_day FROM ys_plan_occ(now() - interval '1 day', now() + interval '2 days') o JOIN ys_users u ON u.id = o.owner_id AND u.active WHERE o.remind_min IS NOT NULL AND o.occurs_at - make_interval(mins => o.remind_min) <= now() AND o.occurs_at - make_interval(mins => o.remind_min) > now() - interval '15 minutes' AND o.occurs_at > now() - interval '5 minutes'), ins AS (INSERT INTO ys_plan_sent (item_id, occurs_at) SELECT item_id, occurs_at FROM due ON CONFLICT DO NOTHING RETURNING item_id, occurs_at), nt AS (INSERT INTO ys_notifications (recipient_id, kind, title, body, link, actor_name) SELECT d.owner_id, 'plan_reminder', d.title, CASE WHEN d.all_day THEN 'Today' ELSE 'At ' || ltrim(to_char(d.occurs_at AT TIME ZONE d.tz, 'HH12:MI AM'), '0') END, '#/plan', 'My Plan' FROM due d JOIN ins ON ins.item_id = d.item_id AND ins.occurs_at = d.occurs_at RETURNING 1), tidy AS (DELETE FROM ys_plan_sent WHERE occurs_at < now() - interval '3 days' RETURNING 1) SELECT (SELECT count(*) FROM nt) AS reminders_sent", options: {} } } });

const hourly = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.3, config: { name: 'Every Hour', position: [0, 240], parameters: { rule: { interval: [{ field: 'hours', hoursInterval: 1, triggerAtMinute: 3 }] } } } });
const findDigest = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Who Gets A Morning Email', position: [224, 240], executeOnce: true, parameters: { operation: 'executeQuery', query: "WITH u AS (SELECT u.id, u.email, u.name, coalesce(p.tz, (SELECT i.tz FROM ys_plan_items i WHERE i.owner_id = u.id ORDER BY i.updated_at DESC LIMIT 1), 'America/Chicago') AS tz FROM ys_users u LEFT JOIN ys_plan_prefs p ON p.owner_id = u.id WHERE u.active AND coalesce(p.digest, true) AND (u.email_verified OR u.google_sub IS NOT NULL) AND u.parent_email IS NULL AND coalesce(u.consent_status, '') NOT IN ('pending', 'approved', 'declined') AND u.email NOT LIKE '%.invalid' AND EXISTS (SELECT 1 FROM ys_plan_items i WHERE i.owner_id = u.id)), due AS (SELECT * FROM u WHERE extract(hour FROM now() AT TIME ZONE u.tz) = 7 AND NOT EXISTS (SELECT 1 FROM ys_plan_prefs p WHERE p.owner_id = u.id AND p.last_digest = (now() AT TIME ZONE u.tz)::date)) SELECT d.id, d.email, d.name, d.tz, to_char((now() AT TIME ZONE d.tz)::date, 'YYYY-MM-DD') AS day, to_char(now() AT TIME ZONE d.tz, 'FMDay, FMMonth FMDD') AS day_label, (SELECT json_agg(json_build_object('title', o.title, 'kind', o.kind, 'time', CASE WHEN o.all_day THEN 'All day' ELSE ltrim(to_char(o.occurs_at AT TIME ZONE d.tz, 'HH12:MI AM'), '0') END, 'notes', o.notes) ORDER BY o.all_day DESC, o.occurs_at) FROM ys_plan_occ(((now() AT TIME ZONE d.tz)::date)::timestamp AT TIME ZONE d.tz, (((now() AT TIME ZONE d.tz)::date + 1)::timestamp) AT TIME ZONE d.tz) o WHERE o.owner_id = d.id) AS items FROM due d", options: {} } } });
const writeEmail = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Write Morning Email', position: [448, 240], parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "// Y Square - My Plan: writes the 7am \"Your plan today\" email for each person who has something planned today.\n// Nothing is sent to accounts under 13 (the query leaves them out) or when the day is empty.\nfunction esc(v) { return String(v == null ? '' : v).replace(/[&<>\"']/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', \"'\": '&#39;' }[c]; }); }\nvar COLORS = { meal: '#16a34a', workout: '#ea580c', study: '#2563eb', event: '#7c3aed', task: '#0891b2', other: '#64748b' };\nvar LABELS = { meal: 'Meal', workout: 'Workout', study: 'Study', event: 'Event', task: 'Task', other: 'Plan' };\nreturn $input.all().map(function (it) { return it.json; }).filter(function (r) { return r.id && r.email && Array.isArray(r.items) && r.items.length; }).map(function (r) {\n  var first = String(r.name || '').trim().split(/\\s+/)[0] || 'there';\n  var rows = r.items.slice(0, 30).map(function (i) {\n    var c = COLORS[i.kind] || COLORS.other;\n    return '<tr><td style=\"padding:10px 12px 10px 0;white-space:nowrap;color:#475569;font-size:14px;vertical-align:top\">' + esc(i.time) + '</td>' +\n      '<td style=\"padding:10px 0;border-left:3px solid ' + c + ';padding-left:12px\"><div style=\"font-size:15px;font-weight:600;color:#0f172a\">' + esc(i.title) + '</div>' +\n      '<div style=\"font-size:12px;color:' + c + ';font-weight:600\">' + esc(LABELS[i.kind] || 'Plan') + '</div>' +\n      (i.notes ? '<div style=\"font-size:13px;color:#64748b;margin-top:2px\">' + esc(i.notes) + '</div>' : '') + '</td></tr>';\n  }).join('');\n  var html = '<div style=\"font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;max-width:560px;margin:0 auto;padding:24px;color:#0f172a\">' +\n    '<div style=\"font-size:13px;font-weight:700;letter-spacing:.4px;color:#4f46e5;text-transform:uppercase\">Y Square - My Plan</div>' +\n    '<h1 style=\"font-size:22px;margin:8px 0 4px\">Good morning, ' + esc(first) + '!</h1>' +\n    '<p style=\"margin:0 0 16px;color:#475569\">Here is your plan for ' + esc(r.day_label) + '.</p>' +\n    '<table role=\"presentation\" style=\"border-collapse:collapse;width:100%\">' + rows + '</table>' +\n    '<p style=\"margin:22px 0\"><a href=\"https://ysquareai.com/#/plan\" style=\"background:#4f46e5;color:#fff;text-decoration:none;padding:10px 18px;border-radius:10px;font-weight:600;display:inline-block\">Open My Plan</a></p>' +\n    '<p style=\"font-size:12px;color:#94a3b8;margin:0\">You get this email because you have items in My Plan on Y Square. To stop it, open My Plan, choose Settings and turn off the morning email.</p></div>';\n  return { json: { id: r.id, day: r.day, email: r.email, subject: 'Your plan for ' + r.day_label, html: html } };\n});" } } });
const sendEmail = node({ type: 'n8n-nodes-base.gmail', version: 2.2, config: { name: 'Send Morning Email', position: [672, 240], onError: 'continueRegularOutput', parameters: { resource: 'message', operation: 'send', sendTo: '={{ $json.email }}', subject: '={{ $json.subject }}', emailType: 'html', message: '={{ $json.html }}', options: { appendAttribution: false, senderName: 'Y Square' } } } });
const markSent = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Mark Email Sent', position: [896, 240], parameters: { operation: 'executeQuery', query: "INSERT INTO ys_plan_prefs (owner_id, last_digest) VALUES ($1, $2::date) ON CONFLICT (owner_id) DO UPDATE SET last_digest = EXCLUDED.last_digest, updated_at = now() RETURNING owner_id", options: { queryReplacement: "={{ [ $('Write Morning Email').item.json.id, $('Write Morning Email').item.json.day ] }}" } } } });

export default workflow('ys-plan-reminders', 'Y Square - My Plan Reminders')
  .add(every5).to(sendReminders)
  .add(hourly).to(findDigest).to(writeEmail).to(sendEmail).to(markSent);
